### ISSUE TITLE
Vouching Functionality

### ISSUE THREAD

**Issue by RonTuretzky** [BreadchainCoop/obUSD-hackathon#5]
These are the entrypoints
`vouch(bytes32 projectApprovalAttestation, bytes32 identityAttestation)`
`vouch(bytes32 projectApprovalAttestation)`

In any given vouch , there are 4 possible scenarios: 
- Voucher has already vouched and project has already been vouched by someone else
	- No need to prove the voucher's identity or the project's validity 
- Voucher has not already vouched and the project has already been vouched by someone else
	- Need to prove the voucher's identity , don't need to prove project
- Voucher has already vouched and the project has not already been vouched for 
	- Need to prove the project's validity 
- Voucher has not already vouched and the project has not been vouched for 
	- Need to prove the voucher's validity and the project's validity 
The following flowchart explains the process that must be done for each scenario. 
`vouch(bytes32 approvedProjectAttestation)`

This function should 

- [ ] Add the project to `currentProjects` if the project is not already included 
- [ ] Should utilize   `validateProject(bytes32 approvedProjectAttestation) (Dependency on #3 #4 , please proceed with empty function declarations if blocked)
- [ ] should initialize projects expiry 
- [ ] unit tests

**Comment by WillyDallas** [comment]
should also
- [ ]  increment the number of vouches a project has
